# Backpropagation Using Classification Simple Intuition

In [58]:
import numpy as np
import pandas as pd

In [59]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa','profile_score','placed'])
df

   cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [60]:
#layer_dims = [2(input_neuron), 2(hidden_neuron), 1(output_neuron)]
def initialize_parameters(layer_dims):
  np.random.seed(3)    # Fixes randomness so results are reproducible
  parameters = {}      # Store: [[W1, b1] ,[W2, b2]]
  L = len(layer_dims)

  for l in range(1,L): # We creates weight between layer0 and layer1
    parameters['W'+str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters['b'+str(l)] = np.zeros((layer_dims[l],1))
  return parameters

In [61]:
#Activation Sigmoid
def sigmoid(Z):
  A = 1/(1+np.exp(-Z))
  return A

In [62]:
# If First layer, A_prev = input features X and  If Hidden layer, A_prev = output of previous activation
def linear_forward(A_prev, W, b):
  Z = np.dot(W.T, A_prev) + b
  A = sigmoid(Z)
  return A

In [63]:
#Forward Propagation
def L_layer_forward(X, parameters): # X-Input Features, Parameters-List containing all weights and biases
  A = X
  L = len(parameters) // 2     # Parameters [[W1,b1],[W2,b2]] which means 4//2 = 2

  for l in range(1, L+1):
    A_prev = A             # Save the previous layer’s output
    W1 = parameters['W' + str(l)]
    b1 = parameters['b' + str(l)]
    # print("A" + str(l-1) + " : ", A_prev)
    # print("W" + str(l) + " : ", W1)
    # print("b" + str(l) + " : ", b1)
    # print("--"*20)

    A = linear_forward(A_prev, W1, b1)
    # print("A" + str(l) + " : ", A)
    # print("**"*20)  # readability

  return A, A_prev   # A Output of Current, A_prev previous layer’s activation

In [64]:
def update_parameters(parameters, y, y_hat, A1, X):
  # Output Layer
  parameters['W2'][0][0] += (0.001 * (y-y_hat)*A1[0][0]) # Output of hidden neuron A11 -> O11
  parameters['W2'][1][0] += (0.001 * (y-y_hat)*A1[1][0]) # Output of hidden neuron A12 -> O12
  parameters['b2'][0][0] += (0.001 * (y-y_hat))

  # Hidden Layer
  parameters['W1'][0][0] += (0.001 * (y-y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0]) #A100 -> O11
  parameters['W1'][0][1] += (0.001 * (y-y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0]) #A100 -> O11
  parameters['b1'][0][0] += (0.001 * (y-y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] += (0.001 * (y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] += (0.001 * (y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] += (0.001 * (y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [65]:
# # change for student X=values[i] and y=values[i][0] change the value of i according to (0)1st,(1)2nd,(3rd)2,(4th)3 student
# X = df[['cgpa','profile_score']].values[3].reshape(2,1) # shape (no. of features, no. of training sample)
# y = df[['placed']].values[3][0]

# #Parameter initialization
# parameters = initialize_parameters([2,2,1])

# y_hat, A1 = L_layer_forward(X, parameters)
# y_hat = float(y_hat[0][0])

# update_parameters(parameters, y, y_hat, A1, X)
# print('Loss for this student - ', -y*np.log(y_hat)-(1-y)*np.log(1-y_hat))
# parameters

In [66]:
#epochs implementation
parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):
    X = df[['cgpa','profile_score']].values[j].reshape(2,1) #shape(no. of features, no. of training samples)
    y = df[['placed']].values[j][0]

    #parameter initialization
    y_hat, A1 = L_layer_forward(X, parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters, y, y_hat, A1, X)

    Loss.append(-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())
parameters

Epoch -  1 Loss -  0.6941717414861723
Epoch -  2 Loss -  0.6941618840080915
Epoch -  3 Loss -  0.6941520705403675
Epoch -  4 Loss -  0.6941423008716868
Epoch -  5 Loss -  0.6941325747917801
Epoch -  6 Loss -  0.6941228920914183
Epoch -  7 Loss -  0.694113252562406
Epoch -  8 Loss -  0.6941036559975762
Epoch -  9 Loss -  0.6940941021907857
Epoch -  10 Loss -  0.694084590936909
Epoch -  11 Loss -  0.6940751220318339
Epoch -  12 Loss -  0.6940656952724554
Epoch -  13 Loss -  0.6940563104566712
Epoch -  14 Loss -  0.694046967383376
Epoch -  15 Loss -  0.6940376658524566
Epoch -  16 Loss -  0.694028405664787
Epoch -  17 Loss -  0.694019186622223
Epoch -  18 Loss -  0.6940100085275969
Epoch -  19 Loss -  0.694000871184713
Epoch -  20 Loss -  0.6939917743983431
Epoch -  21 Loss -  0.6939827179742198
Epoch -  22 Loss -  0.693973701719033
Epoch -  23 Loss -  0.6939647254404246
Epoch -  24 Loss -  0.6939557889469835
Epoch -  25 Loss -  0.6939468920482408
Epoch -  26 Loss -  0.693938034554665
Epoch -  27 Loss -  0.6939292162776569
Epoch -  28 Loss -  0.6939204370295454
Epoch -  29 Loss -  0.6939116966235824
Epoch -  30 Loss -  0.6939029948739378
Epoch -  31 Loss -  0.6938943315956949
Epoch -  32 Loss -  0.6938857066048463
Epoch -  33 Loss -  0.6938771197182885
Epoch -  34 Loss -  0.6938685707538178
Epoch -  35 Loss -  0.693860059530125
Epoch -  36 Loss -  0.6938515858667921
Epoch -  37 Loss -  0.6938431495842858
Epoch -  38 Loss -  0.6938347505039549
Epoch -  39 Loss -  0.6938263884480249
Epoch -  40 Loss -  0.6938180632395932
Epoch -  41 Loss -  0.6938097747026254
Epoch -  42 Loss -  0.6938015226619503
Epoch -  43 Loss -  0.6937933069432554
Epoch -  44 Loss -  0.6937851273730834
Epoch -  45 Loss -  0.6937769837788271
Epoch -  46 Loss -  0.6937688759887246
Epoch -  47 Loss -  0.6937608038318563
Epoch -  48 Loss -  0.6937527671381389
Epoch -  49 Loss -  0.6937447657383236
Epoch -  50 Loss -  0.6937367994639887

{'W1': array([[0.09995316, 0.0991031 ],
        [0.09995955, 0.09910591]]),
 'b1': array([[-0.00025234],
        [-0.00025216]]),
 'W2': array([[0.09624378],
        [0.09624801]]),
 'b2': array([[-0.00775436]])}

#Backpropagation Classification Intuition Using Keras

In [67]:
import numpy as np
import pandas as pd
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa','profile_score','placed'])
df

   cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [68]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [69]:
model = Sequential()

model.add(Dense(2,activation='sigmoid',input_dim=2)) # 2 Input Neurons and 2 Hidden Neurons
model.add(Dense(1,activation='sigmoid')) #Output Neuron

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [70]:
model.summary()  # 2*2(w)+2(b)=6, 2(w)+1(b)=3

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [71]:
#weights that model is taking randomly
model.get_weights()

[array([[-0.49774474,  0.47330153],
        [-0.26692158, -1.1812606 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.44250107],
        [0.7040013 ]], dtype=float32),
 array([0.], dtype=float32)]

In [72]:
#Updates weights according to my intuition
new_weights = [
    np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
    np.array([0.,0.],dtype=np.float32),
    np.array([[0.1],[0.1]],dtype=np.float32),
    np.array([0.],dtype=np.float32)
]

In [73]:
model.set_weights(new_weights)

In [74]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [75]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [76]:
# model.fit(X_train, y_train, epochs=75, verbose=1, batch_size=1)
model.fit(df.iloc[:,0:-1].values, df['placed'].values, epochs=50, verbose=1, batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.6832
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7173
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6569
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7028
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6837
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6717
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7167
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7317
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7312
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6581
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7129
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6829
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6582
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6722
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7285
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6579
Epoch 17/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7302
Epoch 18/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6830
Epoch 19/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7295
Epoch 20/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6841
Epoch 21/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6594
Epoch 22/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6841
Epoch 23/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7269
Epoch 24/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6598
Epoch 25/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7114
Epoch 26/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6842
Epoch 27/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6732
Epoch 28/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6733
Epoch 29/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7049
Epoch 30/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6751
Epoch 31/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7109
Epoch 32/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6600
Epoch 33/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6598
Epoch 34/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7137
Epoch 35/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7045
Epoch 36/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6834
Epoch 37/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6755
Epoch 38/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7043
Epoch 39/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7042
Epoch 40/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6757
Epoch 41/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7005
Epoch 42/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7098
Epoch 43/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7125
Epoch 44/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6846
Epoch 45/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7233
Epoch 46/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7001
Epoch 47/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7092
Epoch 48/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7246
Epoch 49/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7034
Epoch 50/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6839

In [77]:
model.get_weights()

[array([[0.10043032, 0.10043032],
        [0.08625294, 0.08625294]], dtype=float32),
 array([-0.0306276, -0.0306276], dtype=float32),
 array([[0.09197553],
        [0.09197553]], dtype=float32),
 array([-0.01428771], dtype=float32)]