# What We will Do here....
- 1. How to select appropriate optimizer
- 2. How to select number of Nodes in a layer
- 3. How to select number of layers
- 4. All in all one model

- Dataset Link  https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database

In [134]:
import pandas as pd
import numpy as numpy

df = pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [135]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [136]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [137]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [138]:
X.shape

(768, 8)

In [139]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [140]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=1)

# Without experiments taking nodes, layers and optimizers

In [141]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [142]:
model  = Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [143]:
model.fit(X_train, y_train, batch_size=32, epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.6352 - loss: 0.6553 - val_accuracy: 0.6688 - val_loss: 0.6347
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6954 - loss: 0.6038 - val_accuracy: 0.7273 - val_loss: 0.5968
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7199 - loss: 0.5716 - val_accuracy: 0.7597 - val_loss: 0.5682
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7296 - loss: 0.5467 - val_accuracy: 0.7597 - val_loss: 0.5461
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7443 - loss: 0.5268 - val_accuracy: 0.7597 - val_loss: 0.5275
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7459 - loss: 0.5108 - val_accuracy: 0.7662 - val_loss: 0.5136
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7655 - loss: 0.4981 - val_accuracy: 0.7792 - val_loss: 0.5030
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7606 - loss: 0.4885 - val_accuracy: 0.7792 - val_loss: 0.4949
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7590 - loss: 0.4805 - val_accuracy: 0.7727 - val_loss: 0.4878
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.4741 - val_accuracy: 0.7727 - val_loss: 0.4830
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4692 - val_accuracy: 0.7727 - val_loss: 0.4799
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4654 - val_accuracy: 0.7727 - val_loss: 0.4780
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4630 - val_accuracy: 0.7727 - val_loss: 0.4754
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4610 - val_accuracy: 0.7662 - val_loss: 0.4740
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4589 - val_accuracy: 0.7662 - val_loss: 0.4730
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4570 - val_accuracy: 0.7662 - val_loss: 0.4716
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4554 - val_accuracy: 0.7662 - val_loss: 0.4717
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4540 - val_accuracy: 0.7662 - val_loss: 0.4711
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4532 - val_accuracy: 0.7727 - val_loss: 0.4708
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4522 - val_accuracy: 0.7727 - val_loss: 0.4700
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4511 - val_accuracy: 0.7727 - val_loss: 0.4700
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4509 - val_accuracy: 0.7792 - val_loss: 0.4688
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4498 - val_accuracy: 0.7727 - val_loss: 0.4687
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4491 - val_accuracy: 0.7857 - val_loss: 0.4678
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4488 - val_accuracy: 0.7857 - val_loss: 0.4683
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4480 - val_accuracy: 0.7792 - val_loss: 0.4682
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4474 - val_accuracy: 0.7857 - val_loss: 0.4669
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4467 - val_accuracy: 0.7857 - val_loss: 0.4666
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4463 - val_accuracy: 0.7792 - val_loss: 0.4668
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4459 - val_accuracy: 0.7792 - val_loss: 0.4665
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4452 - val_accuracy: 0.7857 - val_loss: 0.4673
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4448 - val_accuracy: 0.7857 - val_loss: 0.4673
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4444 - val_accuracy: 0.7857 - val_loss: 0.4671
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4439 - val_accuracy: 0.7857 - val_loss: 0.4666
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4437 - val_accuracy: 0.7857 - val_loss: 0.4668
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4431 - val_accuracy: 0.7857 - val_loss: 0.4665
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4427 - val_accuracy: 0.7857 - val_loss: 0.4669
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4425 - val_accuracy: 0.7857 - val_loss: 0.4664
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4416 - val_accuracy: 0.7857 - val_loss: 0.4663
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4413 - val_accuracy: 0.7987 - val_loss: 0.4650
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4413 - val_accuracy: 0.7857 - val_loss: 0.4654
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4409 - val_accuracy: 0.7792 - val_loss: 0.4649
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4402 - val_accuracy: 0.7857 - val_loss: 0.4654
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4403 - val_accuracy: 0.7857 - val_loss: 0.4652
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4397 - val_accuracy: 0.7857 - val_loss: 0.4656
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4396 - val_accuracy: 0.7792 - val_loss: 0.4657
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4389 - val_accuracy: 0.7857 - val_loss: 0.4650
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4389 - val_accuracy: 0.7857 - val_loss: 0.4650
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4383 - val_accuracy: 0.7857 - val_loss: 0.4637
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4377 - val_accuracy: 0.7857 - val_loss: 0.4641
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4375 - val_accuracy: 0.7922 - val_loss: 0.4636
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4374 - val_accuracy: 0.7922 - val_loss: 0.4631
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4369 - val_accuracy: 0.7922 - val_loss: 0.4636
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4362 - val_accuracy: 0.7922 - val_loss: 0.4635
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7883 - loss: 0.4360 - val_accuracy: 0.7922 - val_loss: 0.4633
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7834 - loss: 0.4355 - val_accuracy: 0.7922 - val_loss: 0.4634
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4354 - val_accuracy: 0.7922 - val_loss: 0.4639
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7883 - loss: 0.4351 - val_accuracy: 0.7922 - val_loss: 0.4640
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7883 - loss: 0.4352 - val_accuracy: 0.7987 - val_loss: 0.4638
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7899 - loss: 0.4345 - val_accuracy: 0.7922 - val_loss: 0.4632
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7866 - loss: 0.4346 - val_accuracy: 0.7922 - val_loss: 0.4633
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7866 - loss: 0.4337 - val_accuracy: 0.7922 - val_loss: 0.4635
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7883 - loss: 0.4336 - val_accuracy: 0.7922 - val_loss: 0.4636
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.7866 - loss: 0.4333 - val_accuracy: 0.7922 - val_loss: 0.4622
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.7866 - loss: 0.4331 - val_accuracy: 0.7922 - val_loss: 0.4620
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4329 - val_accuracy: 0.7922 - val_loss: 0.4621
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4325 - val_accuracy: 0.7922 - val_loss: 0.4613
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4322 - val_accuracy: 0.7922 - val_loss: 0.4614
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4315 - val_accuracy: 0.7922 - val_loss: 0.4616
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4313 - val_accuracy: 0.7922 - val_loss: 0.4604
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4311 - val_accuracy: 0.7922 - val_loss: 0.4605
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4307 - val_accuracy: 0.7987 - val_loss: 0.4594
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4306 - val_accuracy: 0.7987 - val_loss: 0.4591
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4304 - val_accuracy: 0.7922 - val_loss: 0.4599
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4299 - val_accuracy: 0.7987 - val_loss: 0.4589
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4297 - val_accuracy: 0.7987 - val_loss: 0.4590
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4289 - val_accuracy: 0.7987 - val_loss: 0.4597
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4290 - val_accuracy: 0.7987 - val_loss: 0.4598
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4289 - val_accuracy: 0.8052 - val_loss: 0.4604
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4285 - val_accuracy: 0.7987 - val_loss: 0.4603
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4283 - val_accuracy: 0.7987 - val_loss: 0.4596
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4282 - val_accuracy: 0.7987 - val_loss: 0.4598
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4276 - val_accuracy: 0.7987 - val_loss: 0.4591
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4274 - val_accuracy: 0.8052 - val_loss: 0.4593
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4274 - val_accuracy: 0.8052 - val_loss: 0.4593
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4271 - val_accuracy: 0.8052 - val_loss: 0.4601
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4267 - val_accuracy: 0.8052 - val_loss: 0.4595
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4262 - val_accuracy: 0.8052 - val_loss: 0.4589
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4262 - val_accuracy: 0.8052 - val_loss: 0.4595
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7980 - loss: 0.4256 - val_accuracy: 0.8052 - val_loss: 0.4594
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7883 - loss: 0.4258 - val_accuracy: 0.8117 - val_loss: 0.4591
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4256 - val_accuracy: 0.8117 - val_loss: 0.4591
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7932 - loss: 0.4252 - val_accuracy: 0.8052 - val_loss: 0.4584
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7997 - loss: 0.4249 - val_accuracy: 0.7987 - val_loss: 0.4586
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7932 - loss: 0.4251 - val_accuracy: 0.8052 - val_loss: 0.4593
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7980 - loss: 0.4244 - val_accuracy: 0.8052 - val_loss: 0.4599
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4243 - val_accuracy: 0.8052 - val_loss: 0.4601
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4240 - val_accuracy: 0.8052 - val_loss: 0.4595
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4237 - val_accuracy: 0.8052 - val_loss: 0.4586
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4234 - val_accuracy: 0.7987 - val_loss: 0.4587

# 1. How to select appropriate optimizer

In [144]:
# pip install -U keras-tuner

In [145]:
import keras_tuner as kt

In [146]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  optimizer=hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta'])
  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [147]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [148]:
# find the best optimizer for our problem
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test,y_test))

In [149]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [150]:
model = tuner.get_best_models(num_models=1)[0]
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [151]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7296 - loss: 0.5257 - val_accuracy: 0.7792 - val_loss: 0.4959
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7443 - loss: 0.5099 - val_accuracy: 0.7857 - val_loss: 0.4846
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7573 - loss: 0.4986 - val_accuracy: 0.7857 - val_loss: 0.4779
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7541 - loss: 0.4908 - val_accuracy: 0.8117 - val_loss: 0.4731
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7590 - loss: 0.4835 - val_accuracy: 0.7922 - val_loss: 0.4704
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7638 - loss: 0.4784 - val_accuracy: 0.7857 - val_loss: 0.4692
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7704 - loss: 0.4729 - val_accuracy: 0.8052 - val_loss: 0.4669
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7785 - loss: 0.4688 - val_accuracy: 0.8052 - val_loss: 0.4664
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7785 - loss: 0.4654 - val_accuracy: 0.8052 - val_loss: 0.4657
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7834 - loss: 0.4623 - val_accuracy: 0.7987 - val_loss: 0.4653
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7834 - loss: 0.4597 - val_accuracy: 0.8052 - val_loss: 0.4644
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7752 - loss: 0.4584 - val_accuracy: 0.8117 - val_loss: 0.4646
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7704 - loss: 0.4565 - val_accuracy: 0.8052 - val_loss: 0.4653
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4545 - val_accuracy: 0.7987 - val_loss: 0.4657
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4530 - val_accuracy: 0.7987 - val_loss: 0.4644
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4520 - val_accuracy: 0.7987 - val_loss: 0.4648
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4499 - val_accuracy: 0.7987 - val_loss: 0.4641
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4490 - val_accuracy: 0.7922 - val_loss: 0.4645
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4479 - val_accuracy: 0.7922 - val_loss: 0.4643
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4475 - val_accuracy: 0.7987 - val_loss: 0.4623
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4463 - val_accuracy: 0.7987 - val_loss: 0.4617
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4452 - val_accuracy: 0.7987 - val_loss: 0.4639
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4440 - val_accuracy: 0.7857 - val_loss: 0.4632
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4433 - val_accuracy: 0.7922 - val_loss: 0.4626
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4425 - val_accuracy: 0.7922 - val_loss: 0.4619
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4417 - val_accuracy: 0.7987 - val_loss: 0.4615
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4410 - val_accuracy: 0.7987 - val_loss: 0.4610
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7736 - loss: 0.4404 - val_accuracy: 0.7922 - val_loss: 0.4605
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4403 - val_accuracy: 0.7987 - val_loss: 0.4606
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4389 - val_accuracy: 0.7987 - val_loss: 0.4616
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4381 - val_accuracy: 0.7987 - val_loss: 0.4623
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4381 - val_accuracy: 0.7987 - val_loss: 0.4600
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4370 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7752 - loss: 0.4361 - val_accuracy: 0.7987 - val_loss: 0.4594
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4356 - val_accuracy: 0.7987 - val_loss: 0.4590
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4349 - val_accuracy: 0.7987 - val_loss: 0.4595
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4347 - val_accuracy: 0.7987 - val_loss: 0.4596
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4337 - val_accuracy: 0.7987 - val_loss: 0.4600
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4337 - val_accuracy: 0.7987 - val_loss: 0.4589
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4329 - val_accuracy: 0.7987 - val_loss: 0.4605
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7752 - loss: 0.4327 - val_accuracy: 0.8052 - val_loss: 0.4606
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4320 - val_accuracy: 0.7987 - val_loss: 0.4599
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4315 - val_accuracy: 0.8052 - val_loss: 0.4592
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4311 - val_accuracy: 0.7987 - val_loss: 0.4582
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4311 - val_accuracy: 0.7987 - val_loss: 0.4600
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4304 - val_accuracy: 0.8052 - val_loss: 0.4588
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4302 - val_accuracy: 0.7987 - val_loss: 0.4602
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4294 - val_accuracy: 0.7922 - val_loss: 0.4599
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4292 - val_accuracy: 0.7922 - val_loss: 0.4594
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4288 - val_accuracy: 0.8052 - val_loss: 0.4574
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4284 - val_accuracy: 0.7987 - val_loss: 0.4604
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4287 - val_accuracy: 0.8052 - val_loss: 0.4583
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4272 - val_accuracy: 0.7987 - val_loss: 0.4574
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4264 - val_accuracy: 0.7987 - val_loss: 0.4591
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4262 - val_accuracy: 0.8052 - val_loss: 0.4579
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4261 - val_accuracy: 0.8052 - val_loss: 0.4561
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4257 - val_accuracy: 0.8052 - val_loss: 0.4566
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4252 - val_accuracy: 0.8052 - val_loss: 0.4564
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4244 - val_accuracy: 0.8052 - val_loss: 0.4566
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4242 - val_accuracy: 0.8052 - val_loss: 0.4563
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4239 - val_accuracy: 0.8052 - val_loss: 0.4577
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4236 - val_accuracy: 0.8052 - val_loss: 0.4558
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4237 - val_accuracy: 0.8052 - val_loss: 0.4565
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7915 - loss: 0.4231 - val_accuracy: 0.8052 - val_loss: 0.4558
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7932 - loss: 0.4229 - val_accuracy: 0.8052 - val_loss: 0.4556
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4226 - val_accuracy: 0.7987 - val_loss: 0.4548
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4222 - val_accuracy: 0.7987 - val_loss: 0.4554
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7850 - loss: 0.4216 - val_accuracy: 0.8052 - val_loss: 0.4554
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7834 - loss: 0.4216 - val_accuracy: 0.7987 - val_loss: 0.4589
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4215 - val_accuracy: 0.7987 - val_loss: 0.4579
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7883 - loss: 0.4207 - val_accuracy: 0.8052 - val_loss: 0.4571
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7948 - loss: 0.4204 - val_accuracy: 0.7987 - val_loss: 0.4564
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7899 - loss: 0.4206 - val_accuracy: 0.7987 - val_loss: 0.4565
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4202 - val_accuracy: 0.8052 - val_loss: 0.4551
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4198 - val_accuracy: 0.8052 - val_loss: 0.4537
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4194 - val_accuracy: 0.8052 - val_loss: 0.4543
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4194 - val_accuracy: 0.8117 - val_loss: 0.4543
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4188 - val_accuracy: 0.8052 - val_loss: 0.4559
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4187 - val_accuracy: 0.8052 - val_loss: 0.4563
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4187 - val_accuracy: 0.7987 - val_loss: 0.4551
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4178 - val_accuracy: 0.7987 - val_loss: 0.4558
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4180 - val_accuracy: 0.7987 - val_loss: 0.4565
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4175 - val_accuracy: 0.7987 - val_loss: 0.4568
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4170 - val_accuracy: 0.8052 - val_loss: 0.4569
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4168 - val_accuracy: 0.7987 - val_loss: 0.4575
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4166 - val_accuracy: 0.7987 - val_loss: 0.4585
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4166 - val_accuracy: 0.7987 - val_loss: 0.4565
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4162 - val_accuracy: 0.8052 - val_loss: 0.4562
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4165 - val_accuracy: 0.7987 - val_loss: 0.4563
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7980 - loss: 0.4155 - val_accuracy: 0.7987 - val_loss: 0.4560
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7997 - loss: 0.4150 - val_accuracy: 0.8052 - val_loss: 0.4531
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8013 - loss: 0.4147 - val_accuracy: 0.8052 - val_loss: 0.4533
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4151 - val_accuracy: 0.7987 - val_loss: 0.4569
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4147 - val_accuracy: 0.8052 - val_loss: 0.4535

# 2. Number of Nodes/Neurons in a particular layer

In [152]:
def build_model(hp):
  model = Sequential()

  units = hp.Int('units', min_value=8, max_value=128, step=8)

  model.add(Dense(units=units,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [153]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,directory='mydir',
                        project_name='moin')

Reloading Tuner from mydir/moin/tuner0.json

In [154]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [155]:
tuner.get_best_hyperparameters()[0].values

{'units': 48}

In [156]:
model = tuner.get_best_models(num_models=1)[0]

In [157]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7638 - loss: 0.5335 - val_accuracy: 0.8052 - val_loss: 0.5200
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.5089 - val_accuracy: 0.8052 - val_loss: 0.5020
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4927 - val_accuracy: 0.7987 - val_loss: 0.4890
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4818 - val_accuracy: 0.8052 - val_loss: 0.4799
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4729 - val_accuracy: 0.8117 - val_loss: 0.4755
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4660 - val_accuracy: 0.8052 - val_loss: 0.4736
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4619 - val_accuracy: 0.7987 - val_loss: 0.4710
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4587 - val_accuracy: 0.7922 - val_loss: 0.4696
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4560 - val_accuracy: 0.7987 - val_loss: 0.4684
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4537 - val_accuracy: 0.7987 - val_loss: 0.4680
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4517 - val_accuracy: 0.8052 - val_loss: 0.4668
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4497 - val_accuracy: 0.7987 - val_loss: 0.4662
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4482 - val_accuracy: 0.7922 - val_loss: 0.4646
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4471 - val_accuracy: 0.7922 - val_loss: 0.4644
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4464 - val_accuracy: 0.7922 - val_loss: 0.4652
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4456 - val_accuracy: 0.7922 - val_loss: 0.4639
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4440 - val_accuracy: 0.7922 - val_loss: 0.4635
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4428 - val_accuracy: 0.7922 - val_loss: 0.4617
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4422 - val_accuracy: 0.7922 - val_loss: 0.4620
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7769 - loss: 0.4414 - val_accuracy: 0.7922 - val_loss: 0.4633
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4409 - val_accuracy: 0.7922 - val_loss: 0.4628
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7850 - loss: 0.4413 - val_accuracy: 0.7922 - val_loss: 0.4644
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4397 - val_accuracy: 0.7922 - val_loss: 0.4629
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4379 - val_accuracy: 0.7922 - val_loss: 0.4635
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4380 - val_accuracy: 0.7987 - val_loss: 0.4620
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7785 - loss: 0.4366 - val_accuracy: 0.7922 - val_loss: 0.4630
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4364 - val_accuracy: 0.7922 - val_loss: 0.4631
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4364 - val_accuracy: 0.7987 - val_loss: 0.4625
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4347 - val_accuracy: 0.7922 - val_loss: 0.4633
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4347 - val_accuracy: 0.7922 - val_loss: 0.4626
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4341 - val_accuracy: 0.7922 - val_loss: 0.4644
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4330 - val_accuracy: 0.7922 - val_loss: 0.4641
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4322 - val_accuracy: 0.7922 - val_loss: 0.4645
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4314 - val_accuracy: 0.7922 - val_loss: 0.4637
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4309 - val_accuracy: 0.7922 - val_loss: 0.4645
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4309 - val_accuracy: 0.7987 - val_loss: 0.4647
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4298 - val_accuracy: 0.7922 - val_loss: 0.4643
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4289 - val_accuracy: 0.7922 - val_loss: 0.4639
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4283 - val_accuracy: 0.7987 - val_loss: 0.4646
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4282 - val_accuracy: 0.8052 - val_loss: 0.4654
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4273 - val_accuracy: 0.8052 - val_loss: 0.4648
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4271 - val_accuracy: 0.7987 - val_loss: 0.4636
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4274 - val_accuracy: 0.7987 - val_loss: 0.4643
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4259 - val_accuracy: 0.7922 - val_loss: 0.4640
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4253 - val_accuracy: 0.8052 - val_loss: 0.4643
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4242 - val_accuracy: 0.7922 - val_loss: 0.4648
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4245 - val_accuracy: 0.8052 - val_loss: 0.4656
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4238 - val_accuracy: 0.8052 - val_loss: 0.4658
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4230 - val_accuracy: 0.8052 - val_loss: 0.4653
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4234 - val_accuracy: 0.7987 - val_loss: 0.4651
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4221 - val_accuracy: 0.8052 - val_loss: 0.4645
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4215 - val_accuracy: 0.8052 - val_loss: 0.4660
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4212 - val_accuracy: 0.7987 - val_loss: 0.4651
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4210 - val_accuracy: 0.7922 - val_loss: 0.4666
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4206 - val_accuracy: 0.8117 - val_loss: 0.4666
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4191 - val_accuracy: 0.7857 - val_loss: 0.4661
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4190 - val_accuracy: 0.7857 - val_loss: 0.4671
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4185 - val_accuracy: 0.7922 - val_loss: 0.4656
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4183 - val_accuracy: 0.7922 - val_loss: 0.4667
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4177 - val_accuracy: 0.7922 - val_loss: 0.4675
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4172 - val_accuracy: 0.7922 - val_loss: 0.4685
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4174 - val_accuracy: 0.7987 - val_loss: 0.4685
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4165 - val_accuracy: 0.7922 - val_loss: 0.4685
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4168 - val_accuracy: 0.7857 - val_loss: 0.4672
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4153 - val_accuracy: 0.7857 - val_loss: 0.4658
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4160 - val_accuracy: 0.7857 - val_loss: 0.4664
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4148 - val_accuracy: 0.7987 - val_loss: 0.4675
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4140 - val_accuracy: 0.7987 - val_loss: 0.4672
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4147 - val_accuracy: 0.7922 - val_loss: 0.4681
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4133 - val_accuracy: 0.7987 - val_loss: 0.4681
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4134 - val_accuracy: 0.7987 - val_loss: 0.4668
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4129 - val_accuracy: 0.8052 - val_loss: 0.4683
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4126 - val_accuracy: 0.8052 - val_loss: 0.4684
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4122 - val_accuracy: 0.8052 - val_loss: 0.4656
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4123 - val_accuracy: 0.8052 - val_loss: 0.4663
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4108 - val_accuracy: 0.8052 - val_loss: 0.4660
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4112 - val_accuracy: 0.7987 - val_loss: 0.4687
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4101 - val_accuracy: 0.8052 - val_loss: 0.4693
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.4098 - val_accuracy: 0.8052 - val_loss: 0.4683
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4097 - val_accuracy: 0.8052 - val_loss: 0.4677
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4097 - val_accuracy: 0.8052 - val_loss: 0.4680
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4092 - val_accuracy: 0.8052 - val_loss: 0.4685
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4098 - val_accuracy: 0.8117 - val_loss: 0.4700
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.4085 - val_accuracy: 0.8052 - val_loss: 0.4668
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4084 - val_accuracy: 0.7987 - val_loss: 0.4666
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4082 - val_accuracy: 0.8117 - val_loss: 0.4673
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4072 - val_accuracy: 0.8117 - val_loss: 0.4664
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4064 - val_accuracy: 0.8117 - val_loss: 0.4662
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4066 - val_accuracy: 0.7987 - val_loss: 0.4663
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4060 - val_accuracy: 0.7922 - val_loss: 0.4662
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.4059 - val_accuracy: 0.7987 - val_loss: 0.4662
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4058 - val_accuracy: 0.8052 - val_loss: 0.4699
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4048 - val_accuracy: 0.7987 - val_loss: 0.4685
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4043 - val_accuracy: 0.8117 - val_loss: 0.4689

# 3. How to Select Number of Layers

In [158]:
def build_model(hp):
  model = Sequential()

  model.add(Dense(72,activation='relu',input_dim=8)) # 1st layer
  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
     model.add(Dense(72,activation='relu')) # other layers
  model.add(Dense(1,activation='sigmoid')) #output layer

  model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [159]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3,directory='mydir',
                        project_name='naseem')

Reloading Tuner from mydir/naseem/tuner0.json

In [160]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [161]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 10}

In [162]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 50 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [163]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.7720 - loss: 0.4634 - val_accuracy: 0.8312 - val_loss: 0.4895
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4356 - val_accuracy: 0.7987 - val_loss: 0.4881
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4145 - val_accuracy: 0.8117 - val_loss: 0.4948
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4227 - val_accuracy: 0.7987 - val_loss: 0.5034
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.3916 - val_accuracy: 0.8052 - val_loss: 0.5352
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8176 - loss: 0.3826 - val_accuracy: 0.7857 - val_loss: 0.5271
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8257 - loss: 0.3640 - val_accuracy: 0.7987 - val_loss: 0.5221
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8404 - loss: 0.3477 - val_accuracy: 0.8182 - val_loss: 0.5893
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8355 - loss: 0.3379 - val_accuracy: 0.7857 - val_loss: 0.5630
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3260 - val_accuracy: 0.7857 - val_loss: 0.5383
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3000 - val_accuracy: 0.7857 - val_loss: 0.6113
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.2842 - val_accuracy: 0.7987 - val_loss: 0.6073
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.2882 - val_accuracy: 0.7403 - val_loss: 0.6376
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9055 - loss: 0.2325 - val_accuracy: 0.7857 - val_loss: 0.7131
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2389 - val_accuracy: 0.7662 - val_loss: 0.6985
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8632 - loss: 0.2656 - val_accuracy: 0.8182 - val_loss: 0.6951
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9121 - loss: 0.2058 - val_accuracy: 0.7208 - val_loss: 0.9271
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9316 - loss: 0.1799 - val_accuracy: 0.7273 - val_loss: 1.0731
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8925 - loss: 0.2185 - val_accuracy: 0.7532 - val_loss: 0.8138
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9218 - loss: 0.1866 - val_accuracy: 0.7792 - val_loss: 0.9998
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9169 - loss: 0.1839 - val_accuracy: 0.7857 - val_loss: 0.9975
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9349 - loss: 0.1651 - val_accuracy: 0.7597 - val_loss: 0.9247
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9479 - loss: 0.1295 - val_accuracy: 0.7468 - val_loss: 1.1057
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9104 - loss: 0.2162 - val_accuracy: 0.7468 - val_loss: 0.8479
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9544 - loss: 0.1214 - val_accuracy: 0.7208 - val_loss: 1.2503
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9625 - loss: 0.0917 - val_accuracy: 0.7857 - val_loss: 1.3918
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9332 - loss: 0.1925 - val_accuracy: 0.7857 - val_loss: 0.9166
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9316 - loss: 0.1837 - val_accuracy: 0.7532 - val_loss: 0.8174
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9381 - loss: 0.1299 - val_accuracy: 0.7532 - val_loss: 1.1700
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9593 - loss: 0.1119 - val_accuracy: 0.7597 - val_loss: 1.4231
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9007 - loss: 0.2517 - val_accuracy: 0.7532 - val_loss: 0.6628
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9251 - loss: 0.1972 - val_accuracy: 0.7857 - val_loss: 0.9596
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9625 - loss: 0.0992 - val_accuracy: 0.7597 - val_loss: 1.3292
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9723 - loss: 0.0706 - val_accuracy: 0.7662 - val_loss: 1.4117
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9772 - loss: 0.0588 - val_accuracy: 0.7532 - val_loss: 1.6324
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0513 - val_accuracy: 0.7468 - val_loss: 1.6107
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9919 - loss: 0.0347 - val_accuracy: 0.7532 - val_loss: 1.7369
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9870 - loss: 0.0513 - val_accuracy: 0.7338 - val_loss: 1.7789
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9707 - loss: 0.0859 - val_accuracy: 0.7727 - val_loss: 1.4861
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9691 - loss: 0.0746 - val_accuracy: 0.7338 - val_loss: 1.3763
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9821 - loss: 0.0463 - val_accuracy: 0.7532 - val_loss: 1.8342
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9756 - loss: 0.1038 - val_accuracy: 0.7273 - val_loss: 1.4120
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9723 - loss: 0.0768 - val_accuracy: 0.7468 - val_loss: 1.2191
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9853 - loss: 0.0453 - val_accuracy: 0.7403 - val_loss: 1.5405
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0410 - val_accuracy: 0.7208 - val_loss: 1.8322
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0593 - val_accuracy: 0.7338 - val_loss: 1.6858
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9739 - loss: 0.0886 - val_accuracy: 0.7338 - val_loss: 1.2345
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9788 - loss: 0.0712 - val_accuracy: 0.7208 - val_loss: 1.2543
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0302 - val_accuracy: 0.7208 - val_loss: 1.8063
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9853 - loss: 0.0306 - val_accuracy: 0.7468 - val_loss: 2.1184
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9479 - loss: 0.1513 - val_accuracy: 0.7662 - val_loss: 1.0886
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9511 - loss: 0.1250 - val_accuracy: 0.7338 - val_loss: 0.8391
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9853 - loss: 0.0587 - val_accuracy: 0.7532 - val_loss: 1.3465
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9967 - loss: 0.0125 - val_accuracy: 0.7273 - val_loss: 1.9105
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0618 - val_accuracy: 0.7338 - val_loss: 1.7649
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9853 - loss: 0.0562 - val_accuracy: 0.7403 - val_loss: 1.3740
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9821 - loss: 0.0635 - val_accuracy: 0.7468 - val_loss: 1.2090
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0492 - val_accuracy: 0.7662 - val_loss: 1.4077
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9951 - loss: 0.0185 - val_accuracy: 0.7468 - val_loss: 1.8997
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0227 - val_accuracy: 0.7273 - val_loss: 2.0737
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0703 - val_accuracy: 0.7273 - val_loss: 1.4789
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9805 - loss: 0.0637 - val_accuracy: 0.7727 - val_loss: 1.3273
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9935 - loss: 0.0198 - val_accuracy: 0.7597 - val_loss: 1.5099
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0110 - val_accuracy: 0.7662 - val_loss: 1.9620
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9951 - loss: 0.0151 - val_accuracy: 0.7273 - val_loss: 2.0503
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9935 - loss: 0.0164 - val_accuracy: 0.7273 - val_loss: 2.1649
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0431 - val_accuracy: 0.7338 - val_loss: 1.7135
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9593 - loss: 0.1117 - val_accuracy: 0.7403 - val_loss: 0.9882
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0727 - val_accuracy: 0.7532 - val_loss: 1.2785
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0307 - val_accuracy: 0.7273 - val_loss: 1.7402
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9870 - loss: 0.0449 - val_accuracy: 0.7143 - val_loss: 1.5868
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9967 - loss: 0.0147 - val_accuracy: 0.7403 - val_loss: 1.5467
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.7338 - val_loss: 1.7913
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.7338 - val_loss: 1.9691
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.7403 - val_loss: 2.0935
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 6.3707e-04 - val_accuracy: 0.7403 - val_loss: 2.2025
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 4.6362e-04 - val_accuracy: 0.7403 - val_loss: 2.2856
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 3.4501e-04 - val_accuracy: 0.7468 - val_loss: 2.3712
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 2.7161e-04 - val_accuracy: 0.7468 - val_loss: 2.4480
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 2.1538e-04 - val_accuracy: 0.7468 - val_loss: 2.5170
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 1.7717e-04 - val_accuracy: 0.7468 - val_loss: 2.5844
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 1.4563e-04 - val_accuracy: 0.7468 - val_loss: 2.6490
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 1.1896e-04 - val_accuracy: 0.7468 - val_loss: 2.7082
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 9.8743e-05 - val_accuracy: 0.7468 - val_loss: 2.7588
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 8.2457e-05 - val_accuracy: 0.7468 - val_loss: 2.8097
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 6.9562e-05 - val_accuracy: 0.7468 - val_loss: 2.8615
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 5.7025e-05 - val_accuracy: 0.7403 - val_loss: 2.9652
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 3.8144e-05 - val_accuracy: 0.7403 - val_loss: 3.1571
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 2.3812e-05 - val_accuracy: 0.7338 - val_loss: 3.3332
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.5957e-05 - val_accuracy: 0.7403 - val_loss: 3.4659
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.0595e-05 - val_accuracy: 0.7403 - val_loss: 3.6036
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 6.9117e-06 - val_accuracy: 0.7403 - val_loss: 3.7124
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 4.6523e-06 - val_accuracy: 0.7468 - val_loss: 3.8029
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 3.2985e-06 - val_accuracy: 0.7468 - val_loss: 3.8876

# Now We will Apply All of them in Single Code

In [164]:
def build_model(hp):
  model = Sequential()

  counter=0

  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
     if counter==0:
      model.add(
           Dense(
              hp.Int('units'+str(i),min_value=8, max_value=128, step=8),
              activation=hp.Choice('activation'+str(i), values=['relu','tanh','sigmoid']),
              input_dim=8
          ),
      )
      model.add(Dropout(hp.Choice('dropout'+str(i), values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))

     else:
      model.add(
          Dense(
              hp.Int('units'+str(i),min_value=8, max_value=128, step=8),
              activation=hp.Choice('activation'+str(i), values=['relu','tanh','sigmoid']),
           ),
      )
      model.add(Dropout(hp.Choice('dropout'+str(i), values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
      counter+=1

  model.add(Dense(1,activation='sigmoid'))

  optimizer=hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta'])
  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [165]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3,directory='mydir',
                        project_name='nasir')

In [166]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 11s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.6818181872367859
Total elapsed time: 00h 00m 20s

In [167]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3,
 'units0': 128,
 'activation0': 'relu',
 'dropout0': 0.7,
 'optimizer': 'sgd',
 'units1': 8,
 'activation1': 'relu',
 'dropout1': 0.1,
 'units2': 8,
 'activation2': 'relu',
 'dropout2': 0.1}

In [168]:
model = tuner.get_best_models(num_models=1)[0]

In [169]:
model.fit(X_train,y_train,epochs=200,initial_epoch=5,validation_data=(X_test,y_test))

Epoch 6/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.5733 - loss: 0.6975 - val_accuracy: 0.6688 - val_loss: 0.6659
Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5749 - loss: 0.6852 - val_accuracy: 0.6623 - val_loss: 0.6603
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6010 - loss: 0.6748 - val_accuracy: 0.6494 - val_loss: 0.6556
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6417 - loss: 0.6573 - val_accuracy: 0.6494 - val_loss: 0.6515
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6205 - loss: 0.6700 - val_accuracy: 0.6494 - val_loss: 0.6485
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6433 - loss: 0.6528 - val_accuracy: 0.6494 - val_loss: 0.6445
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6596 - loss: 0.6526 - val_accuracy: 0.6494 - val_loss: 0.6416
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6401 - loss: 0.6570 - val_accuracy: 0.6494 - val_loss: 0.6389
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.6472 - val_accuracy: 0.6494 - val_loss: 0.6363
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6436 - val_accuracy: 0.6494 - val_loss: 0.6336
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6840 - loss: 0.6305 - val_accuracy: 0.6494 - val_loss: 0.6303
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6645 - loss: 0.6455 - val_accuracy: 0.6494 - val_loss: 0.6283
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6661 - loss: 0.6324 - val_accuracy: 0.6494 - val_loss: 0.6248
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6433 - loss: 0.6328 - val_accuracy: 0.6494 - val_loss: 0.6230
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6661 - loss: 0.6348 - val_accuracy: 0.6494 - val_loss: 0.6202
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6629 - loss: 0.6352 - val_accuracy: 0.6494 - val_loss: 0.6178
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6775 - loss: 0.6136 - val_accuracy: 0.6558 - val_loss: 0.6132
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6759 - loss: 0.6142 - val_accuracy: 0.6623 - val_loss: 0.6105
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6661 - loss: 0.6228 - val_accuracy: 0.6688 - val_loss: 0.6064
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6743 - loss: 0.6119 - val_accuracy: 0.6753 - val_loss: 0.6019
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6840 - loss: 0.6199 - val_accuracy: 0.6753 - val_loss: 0.5986
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6792 - loss: 0.6116 - val_accuracy: 0.6753 - val_loss: 0.5927
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6645 - loss: 0.6135 - val_accuracy: 0.6753 - val_loss: 0.5895
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6710 - loss: 0.6054 - val_accuracy: 0.6753 - val_loss: 0.5853
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6987 - loss: 0.5882 - val_accuracy: 0.6883 - val_loss: 0.5781
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6824 - loss: 0.6042 - val_accuracy: 0.6883 - val_loss: 0.5743
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6726 - loss: 0.5928 - val_accuracy: 0.7143 - val_loss: 0.5683
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6743 - loss: 0.5977 - val_accuracy: 0.7208 - val_loss: 0.5633
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6792 - loss: 0.5984 - val_accuracy: 0.7273 - val_loss: 0.5585
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7068 - loss: 0.5795 - val_accuracy: 0.7273 - val_loss: 0.5529
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6987 - loss: 0.5828 - val_accuracy: 0.7273 - val_loss: 0.5484
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7085 - loss: 0.5717 - val_accuracy: 0.7273 - val_loss: 0.5437
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6857 - loss: 0.5784 - val_accuracy: 0.7338 - val_loss: 0.5411
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7182 - loss: 0.5614 - val_accuracy: 0.7338 - val_loss: 0.5368
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6775 - loss: 0.5756 - val_accuracy: 0.7468 - val_loss: 0.5333
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6938 - loss: 0.5705 - val_accuracy: 0.7532 - val_loss: 0.5298
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5515 - val_accuracy: 0.7468 - val_loss: 0.5242
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5606 - val_accuracy: 0.7468 - val_loss: 0.5197
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6938 - loss: 0.5781 - val_accuracy: 0.7532 - val_loss: 0.5177
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.5671 - val_accuracy: 0.7597 - val_loss: 0.5132
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7052 - loss: 0.5576 - val_accuracy: 0.7597 - val_loss: 0.5097
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5491 - val_accuracy: 0.7597 - val_loss: 0.5061
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5663 - val_accuracy: 0.7597 - val_loss: 0.5053
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7215 - loss: 0.5479 - val_accuracy: 0.7727 - val_loss: 0.5032
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5613 - val_accuracy: 0.7792 - val_loss: 0.5026
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5488 - val_accuracy: 0.7727 - val_loss: 0.5007
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7020 - loss: 0.5576 - val_accuracy: 0.7727 - val_loss: 0.4983
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7215 - loss: 0.5370 - val_accuracy: 0.7727 - val_loss: 0.4963
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5431 - val_accuracy: 0.7727 - val_loss: 0.4952
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5451 - val_accuracy: 0.7727 - val_loss: 0.4933
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5371 - val_accuracy: 0.7792 - val_loss: 0.4929
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5463 - val_accuracy: 0.7727 - val_loss: 0.4917
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5458 - val_accuracy: 0.7727 - val_loss: 0.4912
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5269 - val_accuracy: 0.7792 - val_loss: 0.4886
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7313 - loss: 0.5370 - val_accuracy: 0.7792 - val_loss: 0.4859
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5436 - val_accuracy: 0.7792 - val_loss: 0.4856
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5169 - val_accuracy: 0.7857 - val_loss: 0.4834
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5265 - val_accuracy: 0.7922 - val_loss: 0.4828
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5254 - val_accuracy: 0.7857 - val_loss: 0.4828
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5325 - val_accuracy: 0.7987 - val_loss: 0.4811
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5330 - val_accuracy: 0.7922 - val_loss: 0.4804
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4997 - val_accuracy: 0.7922 - val_loss: 0.4778
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5134 - val_accuracy: 0.7987 - val_loss: 0.4750
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5395 - val_accuracy: 0.7987 - val_loss: 0.4763
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5228 - val_accuracy: 0.7987 - val_loss: 0.4754
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.5296 - val_accuracy: 0.8052 - val_loss: 0.4743
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7362 - loss: 0.5415 - val_accuracy: 0.8052 - val_loss: 0.4738
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5156 - val_accuracy: 0.8052 - val_loss: 0.4735
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5130 - val_accuracy: 0.7987 - val_loss: 0.4719
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7541 - loss: 0.5199 - val_accuracy: 0.7987 - val_loss: 0.4709
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5284 - val_accuracy: 0.7987 - val_loss: 0.4711
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5016 - val_accuracy: 0.7987 - val_loss: 0.4709
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5292 - val_accuracy: 0.7987 - val_loss: 0.4710
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5382 - val_accuracy: 0.7987 - val_loss: 0.4720
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5094 - val_accuracy: 0.7987 - val_loss: 0.4703
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5168 - val_accuracy: 0.7922 - val_loss: 0.4697
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.5143 - val_accuracy: 0.7857 - val_loss: 0.4701
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5064 - val_accuracy: 0.7922 - val_loss: 0.4683
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5072 - val_accuracy: 0.7922 - val_loss: 0.4676
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7638 - loss: 0.5159 - val_accuracy: 0.7922 - val_loss: 0.4675
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5306 - val_accuracy: 0.7922 - val_loss: 0.4682
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.5374 - val_accuracy: 0.7792 - val_loss: 0.4698
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.4931 - val_accuracy: 0.7857 - val_loss: 0.4687
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5314 - val_accuracy: 0.7857 - val_loss: 0.4697
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7264 - loss: 0.5222 - val_accuracy: 0.7857 - val_loss: 0.4692
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5166 - val_accuracy: 0.7792 - val_loss: 0.4694
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5179 - val_accuracy: 0.7792 - val_loss: 0.4695
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5207 - val_accuracy: 0.7792 - val_loss: 0.4710
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5214 - val_accuracy: 0.7792 - val_loss: 0.4706
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5233 - val_accuracy: 0.7727 - val_loss: 0.4713
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7248 - loss: 0.5346 - val_accuracy: 0.7792 - val_loss: 0.4723
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7638 - loss: 0.5163 - val_accuracy: 0.7727 - val_loss: 0.4726
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7459 - loss: 0.5140 - val_accuracy: 0.7727 - val_loss: 0.4727
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7329 - loss: 0.5277 - val_accuracy: 0.7727 - val_loss: 0.4727
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7329 - loss: 0.5162 - val_accuracy: 0.7792 - val_loss: 0.4727
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7378 - loss: 0.5107 - val_accuracy: 0.7792 - val_loss: 0.4745
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7590 - loss: 0.5003 - val_accuracy: 0.7727 - val_loss: 0.4728
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7476 - loss: 0.5136 - val_accuracy: 0.7727 - val_loss: 0.4726
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7541 - loss: 0.4978 - val_accuracy: 0.7727 - val_loss: 0.4715
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7362 - loss: 0.5112 - val_accuracy: 0.7727 - val_loss: 0.4716
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7638 - loss: 0.5155 - val_accuracy: 0.7662 - val_loss: 0.4719
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7427 - loss: 0.5102 - val_accuracy: 0.7662 - val_loss: 0.4724
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7492 - loss: 0.5161 - val_accuracy: 0.7727 - val_loss: 0.4722
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7687 - loss: 0.5020 - val_accuracy: 0.7727 - val_loss: 0.4712
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.4919 - val_accuracy: 0.7727 - val_loss: 0.4704
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.5010 - val_accuracy: 0.7662 - val_loss: 0.4711
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5138 - val_accuracy: 0.7727 - val_loss: 0.4727
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.4952 - val_accuracy: 0.7792 - val_loss: 0.4729
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4900 - val_accuracy: 0.7727 - val_loss: 0.4725
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.4842 - val_accuracy: 0.7662 - val_loss: 0.4718
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5029 - val_accuracy: 0.7662 - val_loss: 0.4714
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5082 - val_accuracy: 0.7662 - val_loss: 0.4716
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.4958 - val_accuracy: 0.7662 - val_loss: 0.4717
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5104 - val_accuracy: 0.7662 - val_loss: 0.4719
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5051 - val_accuracy: 0.7662 - val_loss: 0.4722
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.4993 - val_accuracy: 0.7662 - val_loss: 0.4718
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5030 - val_accuracy: 0.7662 - val_loss: 0.4717
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5014 - val_accuracy: 0.7662 - val_loss: 0.4721
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.4820 - val_accuracy: 0.7662 - val_loss: 0.4714
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4874 - val_accuracy: 0.7662 - val_loss: 0.4710
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.5209 - val_accuracy: 0.7662 - val_loss: 0.4718
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.5308 - val_accuracy: 0.7662 - val_loss: 0.4730
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5007 - val_accuracy: 0.7727 - val_loss: 0.4735
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.5011 - val_accuracy: 0.7662 - val_loss: 0.4727
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4992 - val_accuracy: 0.7662 - val_loss: 0.4723
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5170 - val_accuracy: 0.7662 - val_loss: 0.4734
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.4948 - val_accuracy: 0.7662 - val_loss: 0.4732
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4981 - val_accuracy: 0.7727 - val_loss: 0.4736
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7655 - loss: 0.4928 - val_accuracy: 0.7727 - val_loss: 0.4740
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.4977 - val_accuracy: 0.7727 - val_loss: 0.4742
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.5108 - val_accuracy: 0.7727 - val_loss: 0.4744
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5063 - val_accuracy: 0.7727 - val_loss: 0.4751
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.4958 - val_accuracy: 0.7727 - val_loss: 0.4751
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4838 - val_accuracy: 0.7727 - val_loss: 0.4749
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4935 - val_accuracy: 0.7727 - val_loss: 0.4754
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.5062 - val_accuracy: 0.7727 - val_loss: 0.4761
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.4971 - val_accuracy: 0.7727 - val_loss: 0.4753
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4938 - val_accuracy: 0.7727 - val_loss: 0.4753
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.4991 - val_accuracy: 0.7792 - val_loss: 0.4750
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.5044 - val_accuracy: 0.7792 - val_loss: 0.4746
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.5015 - val_accuracy: 0.7792 - val_loss: 0.4744
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4999 - val_accuracy: 0.7792 - val_loss: 0.4742
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.4825 - val_accuracy: 0.7792 - val_loss: 0.4741
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5019 - val_accuracy: 0.7792 - val_loss: 0.4744
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.5029 - val_accuracy: 0.7792 - val_loss: 0.4750
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.4965 - val_accuracy: 0.7792 - val_loss: 0.4750
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4999 - val_accuracy: 0.7792 - val_loss: 0.4747
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5100 - val_accuracy: 0.7792 - val_loss: 0.4752
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.5128 - val_accuracy: 0.7792 - val_loss: 0.4752
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.4927 - val_accuracy: 0.7792 - val_loss: 0.4763
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.5128 - val_accuracy: 0.7792 - val_loss: 0.4765
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4965 - val_accuracy: 0.7792 - val_loss: 0.4764
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4958 - val_accuracy: 0.7792 - val_loss: 0.4763
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.4998 - val_accuracy: 0.7792 - val_loss: 0.4761
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4844 - val_accuracy: 0.7792 - val_loss: 0.4757
Epoch 161/200